version: '3'
services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_docker
  app:
    build: 
      context: .
      dockerfile: Dockerfile.node
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: api_docker
    depends_on:
      - db
